### ISSUE TITLE
Problème installation OSX Sonoma 14.3

### ISSUE THREAD

**Issue by afbenevides** [ERPLibre/ERPLibre#74]
J'ai tenté d'installé sur OSX et il semble y avoir un problème lié aux venv

found 0 vulnerabilities
\n---- Installing Wkhtmltopdf if needed ----
Wkhtmltopdf already installed
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py", line 856, in move
    os.rename(src, real_dst)
    ~~~~~~~~~^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.venv' -> '.venv.odoo12.0_python3.7.17'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bob/Documents/ERPLibre/./script/version/update_env_version.py", line 723, in <module>
    main()
    ~~~~^^
  File "/Users/bob/Documents/ERPLibre/./script/version/update_env_version.py", line 693, in main
    update.update_environment()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/bob/Documents/ERPLibre/./script/version/update_env_version.py", line 434, in update_environment
    self._update_directory_to_link(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        VENV_FILE, self.expected_venv_name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/bob/Documents/ERPLibre/./script/version/update_env_version.py", line 470, in _update_directory_to_link
    shutil.move(dir_to_check, link_name)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py", line 876, in move
    copy_function(src, real_dst)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py", line 468, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ~~~~^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.venv'
make: *** [install_os] Error 1

**Comment by mathben** [comment]
Il faudrait faire un check avant de faire la commande pour créer le link

Voir
File "/Users/bob/Documents/ERPLibre/./script/version/update_env_version.py", line 470, in _update_directory_to_link

**Comment by mathben** [comment]
Le fixe est ici : https://github.com/ERPLibre/ERPLibre/commit/61cb2d68ab3dd67782f7a8a9768817004c6c3dcb
Je vais faire d'autres tests avant de merger dans master.
Merci
